databases:
  - name: matches
    plan: free
    databaseName: matches
    user: matches

services:
  - type: web
    plan: free
    name: matches
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: matches
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false